### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by pandabadger** [samuelwilliams/PhraseGenerator#11]
Possible to bump the travis config and composer.json for php 8?

> badcow/phrase-generator dev-master requires php ~7.1 -> your php version (8.0.1) does not satisfy that requirement.

Thanks

**Comment by samuelwilliams** [comment]
Thanks for the Issue and the PR. I'll up the compatibility and move the CI to Github workflows.

**Comment by samuelwilliams** [comment]
@pandabadger I have updated the requirements in composer and it is running happily on PHP 8.0. Give it a whirl and tell me what you think :)

**Comment by pandabadger** [comment]
Perfect, thanks!
