### ISSUE TITLE
phpstan w/o -l is basically worthless

### ISSUE THREAD

**Issue by hopeseekr** [samuelwilliams/PhraseGenerator#6]
`phpstan analyse` only does Level 0 tests, which are basically "Does the code parse fully?" and not much else.

I highly encourage you to add `-l max`.

The other problem is that `php analyze` won't work without a directory being specified.  You're going to want to add `src` there.

**Comment by samuelwilliams** [comment]
It'll read from the `phpstan.neon` configuration file which has the paths, level and autoload files specified.

**Comment by hopeseekr** [comment]
Well! I obviously gapped that! Thanks for spelling it out and sorry for wasting time :-/

**Comment by samuelwilliams** [comment]
No worries. Thanks for your contribution!

**Comment by hopeseekr** [comment]
It's an honor to help a fellow Maker!
